export const AGENT_RULES_CONTENT = `---
# Agent Rules — SwiftDocs AI Projects

This file defines how you must work on any project generated by SwiftDocs AI.
Read this file before reading any other documentation.

---

## Rule 1 — Setup Order (Always Follow This)

Do these steps in order. Do not skip or reorder.

**Step 1: Install Skills**
Skills teach you how to work on this project correctly.
Run these commands before writing any code:

\`\`\`bash
npx skills add https://github.com/anthropics/skills --skill frontend-design
npx skills add https://github.com/anthropics/skills --skill skill-creator
npx skills add https://github.com/vercel-labs/skills --skill find-skills
\`\`\`

Additional skills may be listed in the skills/ folder — install those too.

**Step 2: Read Skills**
After installing, read every SKILL.md file before proceeding.

**Step 3: Read Documentation**
Read project docs in this order:
1. PRD.md — what the product is and who it's for
2. TechStack.md — what technologies to use and why
3. DatabaseSchema.md — data models and relationships
4. FolderStructure.md — where every file goes
5. ClaudeContext.md — full project context
6. AgentSystemPrompts.md — your detailed instructions

**Step 4: Scaffold Project**
Create the project using CLI commands only.
Never create files or folders manually.
Always use the latest version of every package.

**Step 5: Build**
Follow the documentation. Build step by step.

---

## Rule 2 — Project Creation (Commands Only)

Never create project files manually. Always use official CLI tools.

### Web / MERN Projects
\`\`\`bash
# Backend
mkdir -p backend/src/{controllers,models,routes,middleware,services,utils}
cd backend
npm init -y
npm install express@latest mongoose@latest dotenv@latest bcryptjs@latest jsonwebtoken@latest cors@latest helmet@latest
npm install -D nodemon@latest

# Frontend — always use Vite
npm create vite@latest frontend -- --template react
cd frontend
npm install
npm install react-router-dom@latest axios@latest
\`\`\`

### Flutter / Mobile Projects
\`\`\`bash
flutter create project_name
cd project_name
flutter pub upgrade --major-versions
\`\`\`

### Python / AI Projects
\`\`\`bash
python -m venv venv
source venv/bin/activate
pip install anthropic langchain openai python-dotenv fastapi uvicorn
pip freeze > requirements.txt
\`\`\`

### Angular Projects
\`\`\`bash
npx @angular/cli@latest new project-name
cd project-name
npm install
\`\`\`

### Vue Projects
\`\`\`bash
npm create vite@latest project-name -- --template vue
cd project-name
npm install
\`\`\`

---

## Rule 3 — Always Use Latest Packages

Before installing any package, verify the latest version:
\`\`\`bash
npm show package-name version
\`\`\`

Always install with @latest:
\`\`\`bash
npm install package-name@latest
\`\`\`

Never hardcode version numbers unless a specific version is required by the project docs.

---

## Rule 4 — No Comments in Code

Do not add any comments to code files.
No inline comments. No block comments. No TODO comments.
Code must be self-explanatory through good naming.

---

## Rule 5 — File Size Limits

| File Type | Max Lines |
|-----------|-----------|
| Frontend component (.jsx) | 80 lines |
| Backend controller | 80 lines |
| Backend service | 120 lines |
| Backend model | 60 lines |
| Backend middleware | 50 lines |
| Backend route file | 40 lines |
| Utility file | 60 lines |

If a file exceeds its limit, split it into smaller focused files.
One file = one responsibility.

---

## Rule 6 — Step by Step Work

Do not write everything at once.
Complete one task, verify it works, then move to the next.

If something is unclear:
- Check the project documentation first
- If still unclear, ask the user before assuming

---

## Rule 7 — Update Documentation After Every Task

After completing any significant task:

1. Update the relevant doc file if anything changed from the original plan
2. Update README.md with what was built
3. Write a short summary of what was done

Summary format:
What Was Done

[task name]: [what was built/changed]
[task name]: [what was built/changed]

Current State
[1-2 sentences on where the project stands]
Suggested Next Steps

[suggestion 1]
[suggestion 2]
[suggestion 3]


---

## Rule 8 — Suggest New Features at End

After completing all requested work, always end your response with:
Suggested Improvements
Based on what was built, here are features worth considering next:

[feature] — [why it would help]
[feature] — [why it would help]
[feature] — [why it would help]


Suggestions must be relevant to the actual project — not generic advice.

---

## Rule 9 — Project Structure Rules

- Controllers are thin — only parse request/response, call services
- All business logic lives in services
- Models contain schema only — no business logic
- No hardcoded values — use environment variables
- All async handlers must handle errors properly
- Never expose sensitive data in API responses (no passwords, no tokens)

---

## Rule 10 — This File is Editable

The project owner may add, remove, or modify rules in this file.
Rules added here apply to all future work on this project.
When new rules are added, acknowledge them before starting work.

---

*Generated by SwiftDocs AI — swiftdocsai.vercel.app*
*Last updated: [date of project generation]*
\`;
