export const PLANS = [
  {
    plan: 'free',
    price: '$0',
    period: '',
    description: 'Perfect for trying out SwiftDocs AI',
    features: [
      '1 project',
      '9 AI-generated documents',
      'All document types',
      'Markdown export',
      'Community support',
    ],
    ctaLabel: 'Get Started Free',
    isPopular: false,
  },
  {
    plan: 'pro',
    price: '$19',
    period: '/month',
    description: 'For founders building seriously',
    features: [
      '10 projects',
      'Unlimited document regeneration',
      'Edit & customize documents',
      'ZIP download all docs',
      'AI Co-founder Chat',
      'Priority generation',
      'Email support',
    ],
    ctaLabel: 'Upgrade to Pro',
    isPopular: true,
  },
  {
    plan: 'team',
    price: '$49',
    period: '/month',
    description: 'For teams shipping together',
    features: [
      'Unlimited projects',
      'Everything in Pro',
      'Team collaboration',
      'Custom AI prompts',
      'Advanced analytics',
      'Dedicated support',
      'SLA guarantee',
    ],
    ctaLabel: 'Start Team Plan',
    isPopular: false,
  },
];
