export const DEFAULT_MERN_VALUE = 'Node.js v20 Express REST API with MongoDB Mongoose and React 19';

export const STACK_CARDS = [
  {
    id: 'flutter_mobile',
    name: 'Flutter 3.24+ Cross-Platform',
    subtitle: 'Dart + Riverpod / BLoC + Dio',
    value: 'Flutter 3.24+ Dart Mobile App with Riverpod State, Dio REST Client, Hive Local Cache and Secure Storage',
    category: 'mobile',
    subCategories: ['cross_platform', 'mobile_commerce'],
    badge: 'Mobile Recommended',
    suitableFor: ['mobile', 'ecommerce', 'saas'],
    color: 'from-sky-500/20 to-blue-500/20 border-sky-500/40 text-sky-600',
    tags: ['Flutter 3.24', 'Dart', 'Riverpod', 'Dio', 'Hive DB', 'Secure Storage'],
    iconType: 'flutter',
    description: 'High-performance cross-platform iOS & Android mobile architecture with reactive Riverpod state and native hardware access.'
  },
  {
    id: 'react_native_expo',
    name: 'React Native (Expo SDK 52+)',
    subtitle: 'TypeScript + Expo Router + Zustand',
    value: 'React Native Expo SDK 52+ with TypeScript, Expo Router, Zustand State, and Axios REST API Client',
    category: 'mobile',
    subCategories: ['cross_platform', 'mobile_commerce'],
    badge: 'Fastest Mobile MVP',
    suitableFor: ['mobile', 'ecommerce', 'saas', 'marketplace'],
    color: 'from-blue-500/20 to-cyan-500/20 border-blue-500/40 text-blue-600',
    tags: ['React Native', 'Expo SDK 52', 'Expo Router', 'Zustand', 'Axios'],
    iconType: 'react_native',
    description: 'Universal mobile app architecture powered by Expo file-based routing and seamless JavaScript / TypeScript developer ecosystem.'
  },
  {
    id: 'swift_native',
    name: 'Swift 6 Native iOS',
    subtitle: 'SwiftUI + SwiftData + Combine',
    value: 'Swift 6 Native iOS App with SwiftUI, SwiftData Local Persistence, and Async/Await URLSession',
    category: 'mobile',
    subCategories: ['native_mobile'],
    badge: 'Pure iOS Native',
    suitableFor: ['mobile'],
    color: 'from-orange-500/20 to-amber-500/20 border-orange-500/40 text-orange-600',
    tags: ['Swift 6', 'SwiftUI', 'SwiftData', 'Combine', 'URLSession'],
    iconType: 'swift',
    description: 'Ultra-responsive native iOS experience optimized for Apple Silicon, iOS 18 widgets, and Apple Pay integrations.'
  },
  {
    id: 'kotlin_native',
    name: 'Kotlin Native Android',
    subtitle: 'Jetpack Compose + Coroutines + Room',
    value: 'Kotlin Native Android App with Jetpack Compose, Kotlin Coroutines, Room DB, and Retrofit2',
    category: 'mobile',
    subCategories: ['native_mobile'],
    badge: 'Pure Android Native',
    suitableFor: ['mobile'],
    color: 'from-purple-500/20 to-indigo-500/20 border-purple-500/40 text-purple-600',
    tags: ['Kotlin 2', 'Jetpack Compose', 'Coroutines', 'Room DB', 'Retrofit2'],
    iconType: 'kotlin',
    description: 'Modern Android architecture leveraging declarative Jetpack Compose UI and robust SQLite Room offline database.'
  },
  {
    id: 'python_fastapi',
    name: 'Python 3.12+ (FastAPI / AI Backend)',
    subtitle: 'Async Python Backend & API',
    value: 'Python 3.12 FastAPI Async API with Pydantic v2, SQLAlchemy 2.0, LangChain and Vector Store',
    category: 'ai_async',
    subCategories: ['mobile_backend', 'ai_async'],
    badge: 'AI & Data Native',
    suitableFor: ['ai', 'saas', 'mobile'],
    color: 'from-blue-500/20 to-indigo-500/20 border-blue-500/40 text-blue-600',
    tags: ['Python 3.12', 'FastAPI', 'Pydantic v2', 'SQLAlchemy 2.0', 'LangChain'],
    iconType: 'python',
    description: 'High-performance async Python backend with automatic OpenAPI documentation, vector indexing, and AI agent streaming.'
  },
  {
    id: 'nextjs_commerce',
    name: 'Next.js 15 Commerce & SaaS',
    subtitle: 'App Router + Stripe + Prisma',
    value: 'Next.js 15 App Router Fullstack with Server Actions, Stripe Checkout, PostgreSQL and Prisma ORM',
    category: 'ecommerce',
    subCategories: ['ecommerce', 'fullstack'],
    badge: 'E-Commerce Leader',
    suitableFor: ['ecommerce', 'marketplace', 'saas'],
    color: 'from-emerald-500/20 to-teal-500/20 border-emerald-500/40 text-emerald-600',
    tags: ['Next.js 15', 'App Router', 'Stripe', 'Prisma ORM', 'PostgreSQL', 'Tailwind'],
    iconType: 'nextjs',
    description: 'High-converting eCommerce and SaaS web platform featuring edge caching, transactional Stripe checkout, and Prisma database.'
  },
  {
    id: 'mern_stack',
    name: 'MERN Stack (Express + Mongo)',
    subtitle: 'Node.js v20+ Express + React 19',
    value: DEFAULT_MERN_VALUE,
    category: 'fullstack',
    subCategories: ['fullstack', 'mobile_backend'],
    badge: 'Universal JavaScript',
    suitableFor: ['saas', 'ecommerce', 'marketplace', 'web'],
    color: 'from-amber-500/20 to-yellow-500/20 border-amber-500/40 text-amber-600',
    tags: ['Node.js v20', 'Express 4', 'MongoDB', 'Mongoose', 'React 19'],
    iconType: 'react',
    description: 'Standard JavaScript fullstack architecture with Express middleware, Mongoose schema models, and React 19 components.'
  },
  {
    id: 'nextjs_fullstack',
    name: 'Next.js 15 Unified Fullstack',
    subtitle: 'App Router + React 19 + Tailwind',
    value: 'Next.js 15 App Router with Server Actions, React 19, and Tailwind CSS v4',
    category: 'fullstack',
    subCategories: ['fullstack'],
    badge: 'Modern Web Standard',
    suitableFor: ['saas', 'marketplace', 'ecommerce', 'web'],
    color: 'from-blue-500/20 to-cyan-500/20 border-blue-500/40 text-blue-600',
    tags: ['Next.js 15', 'App Router', 'Server Actions', 'React 19', 'Tailwind v4'],
    iconType: 'nextjs',
    description: 'Unified React 19 fullstack architecture with file-based routing, serverless API endpoints, and built-in SSR/SSG.'
  },
  {
    id: 'dotnet_csharp',
    name: '.NET 9 (ASP.NET Core API)',
    subtitle: 'Clean Architecture C#',
    value: 'C# .NET 9 ASP.NET Core Web API with Clean Architecture & EF Core 9',
    category: 'enterprise',
    subCategories: ['enterprise'],
    badge: 'Enterprise Grade',
    suitableFor: ['saas', 'enterprise'],
    color: 'from-blue-600/20 to-blue-800/20 border-blue-600/40 text-blue-700',
    tags: ['.NET 9', 'C# 12', 'Clean Architecture', 'EF Core 9', 'Web API'],
    iconType: 'dotnet',
    description: 'Enterprise-grade C# backend architecture with dependency injection and Entity Framework Core migrations.'
  },
  {
    id: 'php_laravel',
    name: 'PHP 8.3 / Laravel 11+',
    subtitle: 'Expressive PHP Web API',
    value: 'PHP 8.3 Laravel 11 API with Eloquent ORM and Form Requests',
    category: 'fullstack',
    subCategories: ['enterprise', 'fullstack'],
    badge: 'Rapid Build',
    suitableFor: ['saas', 'marketplace', 'web'],
    color: 'from-rose-500/20 to-red-500/20 border-rose-500/40 text-rose-600',
    tags: ['PHP 8.3', 'Laravel 11', 'Eloquent ORM', 'Form Requests', 'Artisan'],
    iconType: 'laravel',
    description: 'Robust PHP REST API featuring Eloquent ORM relationships, Form Request validation, and Artisan CLI.'
  },
  {
    id: 'react_spa',
    name: 'React 19 SPA (Vite 6)',
    subtitle: 'Pure Client Application',
    value: 'React 19 Vite 6 Single Page App with Zustand and Axios',
    category: 'decoupled',
    subCategories: ['decoupled'],
    badge: 'Lightweight SPA',
    suitableFor: ['saas', 'ai', 'web'],
    color: 'from-sky-500/20 to-blue-500/20 border-sky-500/40 text-sky-600',
    tags: ['React 19', 'Vite 6', 'Zustand', 'Axios', 'Tailwind CSS'],
    iconType: 'vite',
    description: 'Ultra-fast single page client app with Vite 6 bundling, Zustand state, and Axios API services.'
  }
];
